/* Generated-compatible local types. Regenerated by `convex dev` or `convex codegen`. */
import type { DataModelFromSchemaDefinition,DocumentByName,TableNamesInDataModel,SystemTableNames } from 'convex/server';
import type { GenericId } from 'convex/values';
import schema from '../schema';
export type DataModel = DataModelFromSchemaDefinition<typeof schema>;
export type TableNames = TableNamesInDataModel<DataModel>;
export type Doc<T extends TableNames> = DocumentByName<DataModel,T>;
export type Id<T extends TableNames|SystemTableNames> = GenericId<T>;
