import React from 'react';
import { Heart, MessageCircle, UserPlus, Check, Search, ArrowRight, BookOpen, ChevronRight, LockKeyhole, Plus } from 'lucide-react';
import { Avatar, Button, Empty, relativeTime } from './ui';
import olive from './olive.webp';

export function RequestRow({ request, onOpen, onPray, onFollow, busy }) {
  return <article className="tg-request"><Avatar name={request.authorName} /><div className="tg-request-body"><div className="tg-byline"><strong>{request.authorName}</strong><span>{relativeTime(request.createdAt)}{request.following ? ' · Following' : ''}</span></div><div className="tg-request-title"><button onClick={() => onOpen(request._id)}><h2>{request.title}</h2></button>{request.status === 'answered' && <span className="tg-badge tg-badge-gold">Answered</span>}{request.visibility === 'leaders' && <span className="tg-badge"><LockKeyhole size={12} />Leaders only</span>}</div><p className="tg-request-text">{request.body}</p>{request.latestUpdate && <button className="tg-update-strip" onClick={() => onOpen(request._id)}><MessageCircle size={17} /><span><strong>Update:</strong> {request.latestUpdate.body}</span><ChevronRight size={15} /></button>}<div className="tg-request-actions"><button className={`tg-prayed ${request.prayed ? 'is-active' : ''}`} aria-pressed={request.prayed} disabled={busy} onClick={() => onPray(request)}>{request.prayed ? <Check size={17} /> : <Heart size={17} />} {request.prayed ? 'Prayed' : 'I prayed'}</button><button onClick={() => onOpen(request._id)}><MessageCircle size={17} />{request.latestUpdate ? 'View updates' : 'Encourage'}</button><button className="tg-follow" aria-pressed={request.following} onClick={() => onFollow(request)} disabled={busy}>{request.following ? <Check size={17} /> : <UserPlus size={17} />}{request.following ? 'Following' : 'Follow'}</button></div></div></article>;
}
export function CheckIn({ checkIn, isLeader, onShare, onAsk, onUpdate, onCopy }) {
  return <section className="tg-checkin"><img src={olive} alt="" className="tg-olive" /><h2>This week’s check-in</h2><span className="tg-gold-rule" /><p>{checkIn?.prompt || 'How can we pray for you this week?'}</p><Button onClick={onShare}>Add a request</Button><div className="tg-checkin-links"><button className="tg-text-button" onClick={onUpdate}>Update my request<ArrowRight size={15} /></button>{isLeader && <button className="tg-text-button" onClick={checkIn ? onCopy : onAsk}>{checkIn ? 'Share check-in' : 'Ask for requests'}<ArrowRight size={15} /></button>}</div></section>;
}
export function BoardView({ tab, filter, search, requests, checkIn, isLeader, onTab, onFilter, onSearch, onShare, onOpen, onPray, onFollow, onAsk, onCopy, onPrayerTime, busy, children }) {
  const heading = tab === 'answered' ? 'Remember His faithfulness.' : tab === 'archived' ? 'Held in prayer.' : 'Carry one another.';
  return <><section className="tg-hero"><div><h1>{heading}</h1><span className="tg-gold-rule" /><p>{tab === 'answered' ? 'Stories of gratitude from our community.' : tab === 'archived' ? 'Past requests, with their stories kept close.' : 'A place to share, pray, and see God at work.'}</p></div><Button className="tg-share" onClick={onShare}><Plus size={20} />Share a request</Button></section><div className="tg-board-layout"><main className="tg-feed"><div className="tg-toolbar"><div className="tg-filters" aria-label="Filter requests">{[['all', 'All requests'], ['following', 'Following'], ['mine', 'My requests']].map(([key, label]) => <button key={key} aria-pressed={filter === key} className={filter === key ? 'is-active' : ''} onClick={() => onFilter(key)}>{label}</button>)}</div><label className="tg-search"><Search size={17} /><input aria-label="Search requests" placeholder="Search requests…" value={search} onChange={e => onSearch(e.target.value)} /></label></div>{requests.map(request => <RequestRow key={request._id} request={request} onOpen={onOpen} onPray={onPray} onFollow={onFollow} busy={busy} />)}{children}</main><aside className="tg-sidebar"><CheckIn checkIn={checkIn} isLeader={isLeader} onShare={onShare} onAsk={onAsk} onCopy={onCopy} onUpdate={() => { onTab('board'); onFilter('mine'); }} /><button className="tg-prayer-start" onClick={onPrayerTime}><span className="tg-book-circle"><BookOpen size={24} strokeWidth={1.3} /></span><span><strong>Begin prayer time</strong><small>Set aside a few quiet moments to pray through the requests on the board.</small></span><ChevronRight size={19} /></button><div className="tg-scripture"><span className="tg-gold-rule" /><blockquote>“Bear ye one another’s burdens,<br />and so fulfil the law of Christ.”</blockquote><small>Galatians 6:2 · KJV</small></div><button className="tg-archive-link" onClick={() => onTab(tab === 'archived' ? 'board' : 'archived')}>{tab === 'archived' ? 'Back to ongoing requests' : 'View archived requests'}<ArrowRight size={14} /></button></aside></div></>;
}
export function BoardEmpty({ filter, search, tab, onShare }) {
  return <Empty title={search ? 'No matching requests.' : filter === 'following' ? 'Keep a request close.' : tab === 'answered' ? 'Every story is still unfolding.' : tab === 'archived' ? 'Nothing archived yet.' : 'There’s room for what’s on your heart.'} action={!search && tab === 'board' && <Button onClick={onShare}><Plus size={17} />Share a request</Button>}>{search ? 'Try a different word or clear your search.' : filter === 'following' ? 'Tap Follow on a request to find it here and hear how things are going.' : tab === 'answered' ? 'When someone marks a request answered, its story will be gathered here.' : tab === 'archived' ? 'Archived requests will stay here so you can revisit their stories.' : 'Big or small, you don’t have to carry it alone. Share the first request with your group.'}</Empty>;
}
