import React, { useState } from 'react';
import { usePaginatedQuery, useMutation } from 'convex/react';
import { ArrowLeft, ArrowRight, Heart, Check, X, BookOpen } from 'lucide-react';
import { prayerApi } from './data';
import { Button, Loading, Empty, ErrorNotice, errorMessage } from './ui';

export default function PrayerTime({ onClose }) {
  const { results, status, loadMore } = usePaginatedQuery(prayerApi.board, { status: 'ongoing', filter: 'all', presentation: true }, { initialNumItems: 20 });
  const prayed = useMutation(prayerApi.setPrayed); const [index, setIndex] = useState(0); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [finished, setFinished] = useState(false);
  const request = results[Math.min(index, Math.max(0, results.length - 1))];
  return <div className="tg-prayer-mode"><div className="tg-prayer-mode-top"><span><BookOpen size={18} />A moment in prayer</span><button onClick={onClose} className="tg-close-inline" aria-label="Close prayer time"><X size={22} /></button></div>{status === 'LoadingFirstPage' ? <Loading /> : finished ? <Empty title="Thank you for making room." action={<Button onClick={onClose}>Return to your group<ArrowRight size={17} /></Button>}>Carry these prayers with you into the rest of your day.</Empty> : !request ? <Empty title="A quiet moment together." action={<Button onClick={onClose}>Back to the board</Button>}>There are no ongoing group requests to pray through right now.</Empty> : <><div className="tg-prayer-progress"><span style={{ width: `${((index + 1) / results.length) * 100}%` }} /></div><small className="tg-muted">Request {Math.min(index + 1, results.length)} of {results.length}{status !== 'Exhausted' ? '+' : ''} · Shared with our group</small><article className="tg-prayer-focus"><p className="tg-prayer-person">Praying with {request.authorName}</p><h1>{request.title}</h1><p className="tg-full-text">{request.body}</p>{request.latestUpdate && <div className="tg-prayer-latest"><strong>The latest update</strong><p className="tg-full-text">{request.latestUpdate.body}</p></div>}<ErrorNotice>{error}</ErrorNotice><Button variant="outline" busy={busy} aria-pressed={request.prayed} onClick={async () => { setBusy(true); setError(''); try { await prayed({ requestId: request._id, value: !request.prayed }); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }}>{request.prayed ? <Check size={19} /> : <Heart size={19} />}{request.prayed ? 'Held in prayer' : 'I prayed'}</Button></article><div className="tg-prayer-mode-bottom"><Button variant="quiet" disabled={index === 0} onClick={() => setIndex(i => i - 1)}><ArrowLeft size={18} />Previous</Button>{index >= results.length - 1 && status === 'CanLoadMore' ? <Button onClick={() => loadMore(20)}>Load more requests<ArrowRight size={18} /></Button> : <Button busy={status === 'LoadingMore'} onClick={() => index >= results.length - 1 ? setFinished(true) : setIndex(i => i + 1)}>{index >= results.length - 1 ? 'Finish prayer time' : 'Next request'}<ArrowRight size={18} /></Button>}</div></>}</div>;
}
