import React, { useEffect, useState } from 'react';
import { useMutation, useQuery, usePaginatedQuery, useConvexConnectionState } from 'convex/react';
import { useSearchParams } from 'react-router-dom';
import { Bell, Home, MessageCircle, CircleCheck, UserRound, Plus, X, ArrowRight, WifiOff } from 'lucide-react';
import { prayerApi, copyText, prayerLink } from './data';
import { Avatar, Button, Loading, ErrorNotice, errorMessage } from './ui';
import { BoardView, BoardEmpty } from './Board';
import { RequestForm, CheckInForm } from './RequestForms';
import RequestDetail from './RequestDetail';
import PrayerTime from './PrayerTime';
import Settings from './Settings';
import { Updates, Notifications } from './Activity';

const navigation = [['board', 'Prayer board', 'Board', Home], ['updates', 'Updates', 'Updates', MessageCircle], ['answered', 'Answered', 'Answered', CircleCheck], ['me', 'Your profile', 'Me', UserRound]];
class RequestBoundary extends React.Component {
  state = { failed: false };
  static getDerivedStateFromError() { return { failed: true }; }
  render() { return this.state.failed ? <div className="tg-empty"><h2>This request isn’t available.</h2><p>It may have been removed, or its sharing settings may have changed.</p><Button onClick={this.props.onBack}>Back to your group</Button></div> : this.props.children; }
}
export function AppHeader({ tab, onTab, name, unread = 0 }) {
  return <><header className="tg-header"><button className="tg-brand" onClick={() => onTab('board')}>Together<span className="tg-brand-dot">.</span></button><nav className="tg-desktop-nav" aria-label="Main navigation">{navigation.slice(0, 3).map(([key, label]) => <button key={key} className={tab === key ? 'is-active' : ''} onClick={() => onTab(key)} aria-current={tab === key ? 'page' : undefined}>{label}</button>)}</nav><div className="tg-header-right"><button className="tg-bell" aria-label={`Notifications${unread ? `, ${unread} unread` : ''}`} onClick={() => onTab('notifications')}><Bell size={20} />{unread > 0 && <span />}</button><button aria-label="Your profile and group settings" onClick={() => onTab('me')}><Avatar name={name} small /></button></div></header><nav className="tg-mobile-nav" aria-label="Mobile navigation">{navigation.map(([key, label, mobile, Icon]) => <button key={key} onClick={() => onTab(key)} className={tab === key ? 'is-active' : ''} aria-current={tab === key ? 'page' : undefined}><Icon size={21} strokeWidth={tab === key ? 2.2 : 1.6} /><span>{mobile}</span></button>)}</nav></>;
}
function ConnectedBoard({ tab, filter, onFilter, search, onSearch, viewer, checkIn, onTab, onShare, onOpen, onAsk, onCopy, onPrayerTime, toast }) {
  const [debounced, setDebounced] = useState(search); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  useEffect(() => { const timer = setTimeout(() => setDebounced(search), 250); return () => clearTimeout(timer); }, [search]);
  const query = usePaginatedQuery(prayerApi.board, { status: tab === 'answered' ? 'answered' : tab === 'archived' ? 'archived' : 'ongoing', filter, ...(debounced.trim() ? { search: debounced.trim() } : {}) }, { initialNumItems: 15 });
  const prayed = useMutation(prayerApi.setPrayed); const follow = useMutation(prayerApi.setFollow);
  async function action(fn, message) { setBusy(true); setError(''); try { await fn(); if (message) toast(message); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  return <BoardView {...{ tab, filter, search, checkIn, onFilter, onSearch, onTab, onShare, onOpen, onAsk, onCopy, onPrayerTime, busy }} requests={query.results} isLeader={viewer.member.role !== 'member'} onPray={r => action(() => prayed({ requestId: r._id, value: !r.prayed }), r.prayed ? '' : 'A little reminder that they’re not alone.')} onFollow={r => action(() => follow({ requestId: r._id, value: !r.following }), r.following ? 'Request unfollowed.' : 'You’ll find new updates in your notifications.')}><ErrorNotice>{error}</ErrorNotice>{query.status === 'LoadingFirstPage' && <Loading />}{query.status === 'Exhausted' && !query.results.length && <BoardEmpty {...{ filter, search, tab, onShare }} />}{query.status === 'CanLoadMore' && <div className="tg-load-more"><Button variant="quiet" onClick={() => query.loadMore(15)}>More requests<ArrowRight size={16} /></Button></div>}{query.status === 'LoadingMore' && <Loading label="Loading more requests…" />}</BoardView>;
}
export default function PrayerApp({ viewer }) {
  const [params, setParams] = useSearchParams(); const allowed = ['board', 'updates', 'answered', 'archived', 'me', 'notifications']; const tab = allowed.includes(params.get('view')) ? params.get('view') : 'board'; const requestId = params.get('request'); const selectedCheckInId = params.get('checkin');
  const [filter, setFilter] = useState('all'); const [search, setSearch] = useState(''); const [form, setForm] = useState(false); const [ask, setAsk] = useState(false); const [prayerTime, setPrayerTime] = useState(false); const [notice, setNotice] = useState(''); const [copiedLink, setCopiedLink] = useState('');
  const checkIns = useQuery(prayerApi.checkIns, {}); const unread = useQuery(prayerApi.unreadCount, {}); const connection = useConvexConnectionState();
  const activeCheckIn = checkIns?.find(c => c.open); const selectedCheckIn = selectedCheckInId ? checkIns?.find(c => c._id === selectedCheckInId) : activeCheckIn;
  useEffect(() => { if (!notice) return; const timer = setTimeout(() => setNotice(''), 5000); return () => clearTimeout(timer); }, [notice]);
  function onTab(next) { const p = new URLSearchParams(); if (next !== 'board') p.set('view', next); setParams(p); window.scrollTo({ top: 0 }); }
  function onOpen(id) { const p = new URLSearchParams(params); p.set('request', id); setParams(p); window.scrollTo({ top: 0 }); }
  async function shareCheckIn(id) { const target = prayerLink(`?checkin=${encodeURIComponent(id || activeCheckIn?._id || '')}`); const text = `How can we pray for you this week? Add a request or share an update with our Bible study: ${target}`; try { await copyText(text); setNotice('Check-in invitation copied. Share it in your group text.'); } catch { setCopiedLink(text); } }
  return <div className="tg-surface tg-app">{prayerTime ? <PrayerTime onClose={() => setPrayerTime(false)} /> : <><AppHeader tab={tab} onTab={onTab} name={viewer.name} unread={unread || 0} />{!connection.isWebSocketConnected && <div className="tg-connection" role="status"><WifiOff size={16} />Reconnecting. Please wait for a connection before posting.</div>}<div className="tg-main-wrap">{selectedCheckInId && selectedCheckIn && <div className="tg-checkin-banner"><div><strong>{selectedCheckIn.prompt}</strong><small>{selectedCheckIn.open ? 'Share a request or update an existing one for this check-in.' : 'This check-in has closed. You can still share a request with your group.'}</small></div><Button variant="outline" onClick={() => setForm(true)}><Plus size={16} />Add request</Button></div>}{requestId ? <RequestBoundary key={requestId} onBack={() => onTab('board')}><RequestDetail requestId={requestId} checkInId={selectedCheckIn?.open ? selectedCheckInId : undefined} onBack={() => { const p = new URLSearchParams(params); p.delete('request'); setParams(p); }} toast={setNotice} /></RequestBoundary> : tab === 'me' ? <Settings viewer={viewer} toast={setNotice} onAsk={() => setAsk(true)} /> : tab === 'updates' ? <Updates onOpen={onOpen} /> : tab === 'notifications' ? <Notifications onOpen={onOpen} onCheckIn={id => { const p = new URLSearchParams(); if (id) p.set('checkin', id); setParams(p); }} toast={setNotice} /> : <ConnectedBoard {...{ tab, filter, search, viewer, onTab, onOpen }} onFilter={setFilter} onSearch={setSearch} checkIn={selectedCheckIn?.open ? selectedCheckIn : activeCheckIn} onShare={() => setForm(true)} onAsk={() => setAsk(true)} onCopy={() => shareCheckIn()} onPrayerTime={() => setPrayerTime(true)} toast={setNotice} />}</div><footer className="tg-app-footer"><span>{viewer.group.name}{viewer.group.meetingSchedule ? ` · ${viewer.group.meetingSchedule}` : ''}</span><span>Shared with care. Held in prayer.</span></footer></>}{notice && <div className="tg-toast" role="status">{notice}<button aria-label="Dismiss message" onClick={() => setNotice('')}><X size={16} /></button></div>}{copiedLink && <div className="tg-copy-fallback"><label>Copy this message to share your check-in<textarea readOnly value={copiedLink} onFocus={e => e.target.select()} /></label><Button onClick={() => setCopiedLink('')}>Done</Button></div>}{form && <RequestForm checkInId={selectedCheckIn?.open ? selectedCheckIn._id : activeCheckIn?._id} onClose={() => setForm(false)} onSaved={id => { setForm(false); onOpen(id); setNotice('Your request has been shared with care.'); }} />}{ask && <CheckInForm onClose={() => setAsk(false)} onSaved={id => { setAsk(false); setNotice('Your check-in is open.'); onTab('board'); shareCheckIn(id); }} />}</div>;
}
