import React, { useState } from 'react';
import { useMutation } from 'convex/react';
import { ArrowRight, LockKeyhole, Users, Check } from 'lucide-react';
import { prayerApi } from './data';
import { Button, Field, ErrorNotice, Modal, errorMessage } from './ui';

export function RequestForm({ request, checkInId, onClose, onSaved }) {
  const [title, setTitle] = useState(request?.title || ''); const [body, setBody] = useState(request?.body || ''); const [category, setCategory] = useState(request?.category || 'other'); const [visibility, setVisibility] = useState(request?.visibility || 'group');
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const create = useMutation(prayerApi.createRequest); const edit = useMutation(prayerApi.editRequest);
  return <Modal title={request ? 'Edit your request' : 'What’s on your heart?'} description="Share as much or as little as you like. We’re here to pray with you." onClose={() => !busy && onClose()}><form onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); try { const fields = { title: title.trim(), body: body.trim(), category, visibility }; const id = request ? (await edit({ requestId: request._id, ...fields }), request._id) : await create({ ...fields, ...(checkInId ? { checkInId } : {}) }); onSaved(id); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }}><Field label="What can we pray for?"><input autoFocus required maxLength={140} placeholder="A few words to start…" value={title} onChange={e => setTitle(e.target.value)} /></Field><Field label="Tell us a little more"><textarea required rows={5} maxLength={5000} placeholder="What would you like your group to know?" value={body} onChange={e => setBody(e.target.value)} /></Field><Field label="Category"><select value={category} onChange={e => setCategory(e.target.value)}>{['family', 'health', 'work', 'faith', 'other'].map(c => <option key={c} value={c}>{c[0].toUpperCase() + c.slice(1)}</option>)}</select></Field><fieldset className="tg-visibility"><legend>Who can see this?</legend>{[['group', 'Our group', 'Everyone in our Bible study', Users], ['leaders', 'Leaders only', 'You and the group’s leaders', LockKeyhole]].map(([key, label, hint, Icon]) => <label key={key} className={visibility === key ? 'is-selected' : ''}><input type="radio" name="visibility" value={key} checked={visibility === key} onChange={() => setVisibility(key)} /><Icon size={20} /><span><strong>{label}</strong><small>{hint}</small></span>{visibility === key && <Check size={17} />}</label>)}</fieldset><p className="tg-fine"><LockKeyhole size={13} />This request and its updates will be visible to {visibility === 'leaders' ? 'you and the group’s leaders only' : 'your invited group members'}.</p><ErrorNotice>{error}</ErrorNotice><div className="tg-form-actions"><Button variant="quiet" onClick={onClose} type="button" disabled={busy}>Cancel</Button><Button type="submit" busy={busy}>{request ? 'Save changes' : 'Share request'}<ArrowRight size={17} /></Button></div></form></Modal>;
}
export function CheckInForm({ onClose, onSaved }) {
  const create = useMutation(prayerApi.createCheckIn); const [prompt, setPrompt] = useState('How can we pray for you this week?'); const [closeDate, setCloseDate] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  return <Modal title="Ask for prayer requests" description="Invite your group to share a new request or an update before you gather." onClose={() => !busy && onClose()}><form onSubmit={async e => { e.preventDefault(); setBusy(true); setError(''); try { const id = await create({ prompt: prompt.trim(), ...(closeDate ? { closesAt: new Date(`${closeDate}T23:59:59`).getTime() } : {}) }); onSaved(id); } catch (e) { setError(errorMessage(e)); } finally { setBusy(false); } }}><Field label="Your message"><textarea autoFocus rows={4} maxLength={500} required value={prompt} onChange={e => setPrompt(e.target.value)} /></Field><Field label="Close check-in on (optional)" hint="Members can still share ongoing requests after the check-in closes."><input type="date" value={closeDate} min={new Date().toLocaleDateString('en-CA')} onChange={e => setCloseDate(e.target.value)} /></Field><p className="tg-soft-note">Your group will see this on the board and in their notifications. You can also copy a link to share in your group text.</p><ErrorNotice>{error}</ErrorNotice><div className="tg-form-actions"><Button type="button" variant="quiet" onClick={onClose} disabled={busy}>Cancel</Button><Button type="submit" busy={busy}>Post check-in<ArrowRight size={17} /></Button></div></form></Modal>;
}
